### ISSUE TITLE
Is there any plan to create "Vue" version bim viewer?

### ISSUE THREAD

**Issue by gisfinder** [xeokit/xeokit-bim-viewer#48]
Vue version will be welcome. Thanks so much.

**Comment by Calvin66** [comment]
i want to create "Vue" version bim viewer in my project ,any ideas?

**Comment by xeolabs** [comment]
We have users who have built apps on xeokit using Vue, so we know there's no problem doing it, however it's outside the scope of xeokit at this stage to offer UI framework integrations as part of the product (like THREE, Babylon etc, xeokit is a viewer library that's designed to be agnostic of what UI frameworks are used on top of it, so that you have the freedom to use Vue, React, Angular etc).
