### ISSUE TITLE
DistanceMeasurementPlugin does not work with BIM Viewer

### ISSUE THREAD

**Issue by mbzaven** [xeokit/xeokit-bim-viewer#87]
After creating a new DistanceMeasurementsPlugin like that:
```
const myBIMViewer = new xeokitBimViewerEs.BIMViewer(server, {
    canvasElement: document.getElementById("myCanvas"),
    explorerElement: document.getElementById("myExplorer"),
    toolbarElement: document.getElementById("myToolbar"),
    navCubeCanvasElement: document.getElementById("myNavCubeCanvas"),
    busyModelBackdropElement: document.querySelector(".xeokit-busy-modal-backdrop"),
    externalMetadata: true,
    transparent: true,
    scene: {
      highlightMaterial: {
        fillAlpha: 0.3,
        edgeColor: [1, 1, 0]
      }
    }
  });

const distanceMeasurementTool = new xeokitSdkEs.DistanceMeasurementsPlugin(myBIMViewer.viewer);
distanceMeasurementTool.control.activate();
```
I get a following error in browser console:

> xeokit-sdk.es.js:1 Uncaught TypeError: this._entity.once is not a function
    at Y.set entity [as entity] (xeokit-sdk.es.js:1)
    at new Y (xeokit-sdk.es.js:1)
    at new Gi (xeokit-sdk.es.js:1)
    at Wi.createMeasurement (xeokit-sdk.es.js:1)
    at fe.<anonymous> (xeokit-sdk.es.js:1)
    at fe.fire (xeokit-bim-viewer.es.js:1)
    at HTMLDocument.document.addEventListener._mouseUpListener (xeokit-bim-viewer.es.js:1)

Any help will be appreciated

**Comment by xeolabs** [comment]
Hi, this is not a recommended way to extend BIMViewer, so it's not really a defect.

The BIMViewer class is responsible for coordinating the state of the various xeokit components that make up the application. Attaching a xeokit component externally like this bypasses that logic - for example, the BIMViewer would not be able to make the other tools, like Slice, Select etc mutually-exclusive to the DistanceMeasurement tool.

However, in this case, you're also getting an exception due to (I think) using the xeokit-sdk.js library and xeokit-bim-viewer.js library files together in the same application. That usage pattern has actually not been tested so far, and you've found something that needs to be fixed for that usage to be supported.

I will be adding a new panel to BIMViewer to show measurements though, possible in 2.1 release.

**Comment by satyajitghana** [comment]
any update on this ?

i'm stuck on this error as well

**Comment by xeolabs** [comment]
Not an error - please see comment above.
